Add hint to use flip
ndmitchell/hlint pull request #1616
Opened 2024-10-02 05:58 UTC by josephcsible

2024-12-13 21:00 UTC, zliu41 requested changes
Looks good, please update `hints.md`

2024-12-13 22:04 UTC, josephcsible commented
Done

2024-12-14 03:08 UTC, zliu41 approved these changes

2024-12-14 03:08 UTC, merged

2024-12-14 03:08 UTC, zliu41 commented
Thanks